### ISSUE TITLE
师傅，"远程配置上传失败：undefined"是怎么回事

### ISSUE THREAD

**Issue by wzy105** [monlor/openclash-rules#1]
![}ZE67 NXRR~U32J2WUYUF4](https://user-images.githubusercontent.com/117211092/205585382-fcd21bd9-eed6-4fa2-be22-1415e77bbcd9.png)

**Comment by monlor** [comment]
不清楚你用的是什么工具，可以直接使用subconverter转换工具，config修改成我的规则地址就行
