### ISSUE TITLE
请教一下Openclash 如何使用您的规则，有自己的订阅连接

### ISSUE THREAD

**Issue by garydak** [monlor/openclash-rules#2]

**Comment by monlor** [comment]
用订阅转换工具subconvertor，修改config字段为`https%3A//raw.githubusercontent.com/monlor/openclash-rules/master/ACL4SSR_Online_Full.ini`

**Comment by garydak** [comment]
用在线的订阅转换可以实现吗？suboconvertor工具找不到好用的

**Comment by monlor** [comment]
刚搭建了一个，并且添加了我自用的规则，地址：https://sub.monlor.com (不要滥用哦😯)
![CleanShot 2023-03-06 at 14 44 19@2x](https://user-images.githubusercontent.com/20394007/223037722-873e4f46-3fa0-445d-a33c-df3113f44c73.png)
